[package]
name = "vey-qat"
version = "0.1.0"
license.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Intel qatlib helpers for asynchronous asymmetric crypto"

[dependencies]
libc.workspace = true
log.workspace = true
openssl.workspace = true
openssl-sys.workspace = true
tokio = { workspace = true, features = ["net", "rt", "sync", "time"] }

[build-dependencies]
pkg-config = "0.3"
