---

- hosts: "{{ group | default('vey-proxy') }}"
  roles:
    - role: benchmark
  handlers:
    - ansible.builtin.import_tasks: roles/vey-proxy/handlers/restart.yml
  vars:
    daemon_group: benchmark
