---

- name: Add VEY repo
  ansible.builtin.yum_repository:
    name: vey
    description: VEY repo
    baseurl: https://dl.cloudsmith.io/public/vey-oss/rolling/rpm/el/$releasever/$basearch
    gpgkey: https://dl.cloudsmith.io/public/vey-oss/rolling/gpg.819A41862B04BBE1.key
    enabled: true
    proxy: "{{ vey_repo_proxy | default('_none_') }}"
