---

- name: Install apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Add apt proxy config for VEY repo
  ansible.builtin.template:
    src: apt.conf.d/80vey-proxy
    dest: /etc/apt/apt.conf.d/80vey-proxy
    owner: root
    group: root
    mode: "0644"
  when: vey_repo_proxy is defined

- name: Clear apt proxy config for VEY repo
  ansible.builtin.file:
    path: /etc/apt/apt.conf.d/80vey-proxy
    state: absent
  when: vey_repo_proxy is not defined

- name: Add VEY repo
  ansible.builtin.deb822_repository:
    name: vey-oss
    install_python_debian: true
    types: deb
    uris: 'https://dl.cloudsmith.io/public/vey-oss/rolling/deb/{{ ansible_facts["distribution"]|lower }}'
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: main
    signed_by: https://dl.cloudsmith.io/public/vey-oss/rolling/gpg.819A41862B04BBE1.key
