name: Linux-Extra
permissions: { }

on:
  pull_request:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'main'
      - 'lts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_RUSTFLAGS: -C linker-features=-lld # workaround for vendored-boringssl

jobs:
  build-vendored-g1:
    name: Build vendored
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        feature:
          - vendored-openssl,rustls-ring
          - vendored-tongsuo,rustls-ring
          - vendored-boringssl,rustls-ring
          - vendored-aws-lc,rustls-aws-lc
          - vendored-aws-lc-fips,rustls-aws-lc-fips
        component:
          - vey-proxy
          - vey-bench
          - vey-gateway
          - vey-keyless
        include:
          - feature: vendored-c-ares,rustls-ring
            component: vey-proxy
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libc-ares-dev libssl-dev
      - name: Cargo clean
        run: cargo clean
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings
  build-vendored-g2:
    name: Build vendored
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        feature:
          - vendored-openssl
          - vendored-tongsuo
          - vendored-boringssl
          - vendored-aws-lc
          - vendored-aws-lc-fips
        component:
          - vey-dcgen
          - vey-mkcert
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libssl-dev
      - name: Cargo clean
        run: cargo clean
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings
  openssl-async-job:
    name: Build with OpenSSL Async Job
    runs-on: ubuntu-26.04
    strategy:
      matrix:
        component:
          - vey-keyless
          - vey-gateway
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libssl-dev
      - name: Cargo clean
        run: cargo clean
      - name: Cargo build
        run: cargo build --features openssl-async-job -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --features openssl-async-job -p ${{ matrix.component }} -- --deny warnings
  crypto-mb:
    name: Build with crypto_mb (x86_64)
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libssl-dev libcrypto-mb-dev pkg-config
      - name: Cargo clean
        run: cargo clean
      - name: Cargo build
        run: cargo build -p vey-crypto-mb -p vey-keyless --features crypto-mb
      - name: Cargo clippy
        run: |
          cargo clippy -p vey-crypto-mb -- --deny warnings
          cargo clippy -p vey-keyless --features crypto-mb -- --deny warnings
      - name: Cargo test
        run: |
          lscpu
          cargo test -p vey-crypto-mb
      - name: Cargo test vey-keyless
        run: cargo test -p vey-keyless --features crypto-mb
  qat:
    name: Build with qatlib (linux x86_64)
    runs-on: ubuntu-26.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v7
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libssl-dev libqat-dev libusdm-dev pkg-config
      - name: Cargo clean
        run: cargo clean
      - name: Cargo build
        run: cargo build -p vey-qat -p vey-keyless --features qat
      - name: Cargo clippy
        run: |
          cargo clippy -p vey-qat -- --deny warnings
          cargo clippy -p vey-keyless --features qat -- --deny warnings
      - name: Cargo test
        run: |
          cargo test -p vey-qat
          cargo test -p vey-keyless --features qat
