name: Linux-Basic
permissions: { }

on:
  push:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'main'
      - 'lts/**'
  pull_request:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'main'
      - 'lts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - "1.91"
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install ${{ matrix.rust }} toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libc-ares-dev libssl-dev liblua5.4-dev
      - name: Cargo build
        run: cargo build --features lua54
      - name: Cargo test
        run: cargo test --workspace --features lua54
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto libc-ares-dev libssl-dev liblua5.4-dev
      - name: Cargo clippy
        run: cargo clippy --tests --workspace --features lua54 -- --deny warnings
