name: MacOS-Extra
permissions: { }

on:
  pull_request:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'main'
      - 'lts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build-vendored-g1:
    name: Build vendored
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl,rustls-ring
          - vendored-tongsuo,rustls-ring
          - vendored-boringssl,rustls-ring
          - vendored-aws-lc,rustls-aws-lc
        component:
          - vey-proxy
          - vey-bench
          - vey-gateway
        include:
          - feature: vendored-c-ares,rustls-ring
            component: vey-proxy
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          brew install capnp openssl c-ares
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings
  build-vendored-g2:
    name: Build vendored
    runs-on: macos-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl
          - vendored-tongsuo
          - vendored-boringssl
          - vendored-aws-lc
        component:
          - vey-dcgen
          - vey-mkcert
          - vey-keyless
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Install dependencies
        run: |
          brew install capnp openssl
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }}
      - name: Cargo clippy
        run: cargo clippy --no-default-features --features ${{ matrix.feature }} -p ${{ matrix.component }} -- --deny warnings
