name: StaticLinking
permissions: { }

on:
  pull_request:
    paths-ignore:
      - 'ansible/**'
      - 'doc/**'
      - 'sphinx/**'
      - 'scripts/**'
    branches:
      - 'main'
      - 'lts/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_TARGET_X86_64_PC_WINDOWS_MSVC_RUSTFLAGS: -C target-feature=+crt-static
  VCPKG_ROOT: C:\vcpkg
  VCPKGRS_TRIPLET: x64-windows-static
  AWS_LC_SYS_PREBUILT_NASM: 1

jobs:
  musl-c:
    name: musl-c
    runs-on: ubuntu-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl,rustls-ring
          - vendored-tongsuo,rustls-ring
    steps:
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install capnproto musl-tools
      - name: Cargo build
        run: cargo build --target=x86_64-unknown-linux-musl --no-default-features --features ${{ matrix.feature }},quic,vendored-c-ares
  musl-cxx:
    name: musl-cxx
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rust-lang/rust:nightly-alpine
      env:
        CARGO_TERM_COLOR: always
        RUSTFLAGS: -C target-feature=+crt-static
        UNSTABLE_OPTIONS: -Ztarget-applies-to-host -Zhost-config
    strategy:
      matrix:
        feature:
          - vendored-boringssl,rustls-ring
          - vendored-aws-lc,rustls-aws-lc
          - vendored-aws-lc-fips,rustls-aws-lc-fips
    steps:
      - name: Install base tools
        run: |
          apk add --no-cache git curl
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install dependencies
        run: |
          apk add --no-cache musl-dev linux-headers libstdc++-dev libunwind-static
          apk add --no-cache g++ capnproto-dev clang-libclang cmake make
          apk add --no-cache perl nasm
      - name: Install Go for AWS-LC-FIPS
        if: contains(matrix.feature, 'vendored-aws-lc-fips')
        run: apk add --no-cache go
      - name: Cargo build
        run: cargo $UNSTABLE_OPTIONS build --no-default-features --features ${{ matrix.feature }},quic,vendored-c-ares
  msvc-vcpkg:
    name: msvc-vcpkg
    runs-on: windows-latest
    steps:
      - name: Install common tools
        run: choco install capnproto
      - name: Install lib dependencies (vcpkg)
        run: vcpkg install --triplet=x64-windows-static openssl c-ares
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        run: cargo build --no-default-features --features rustls-ring,quic,c-ares
  msvc-vendored:
    name: msvc-vendored
    runs-on: windows-latest
    strategy:
      matrix:
        feature:
          - vendored-openssl,rustls-ring
          - vendored-tongsuo,rustls-ring
          - vendored-boringssl,rustls-ring
          - vendored-aws-lc,rustls-aws-lc
    steps:
      - name: Install common tools
        run: choco install capnproto
      - name: Install nasm and ninja for BoringSSL
        if: contains(matrix.feature, 'vendored-boringssl')
        run: choco install nasm ninja
      - name: Checkout sources
        uses: actions/checkout@v6
        with:
          submodules: true
      - name: Install rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cargo build
        run: cargo build --no-default-features --features ${{ matrix.feature }},quic,vendored-c-ares
